Importing libraries

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Loading the dataset

In [30]:
dataset = pd.read_csv("/content/Social_Network_Ads.csv")

In [32]:
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [34]:
dataset.shape

(400, 3)

In [35]:
dataset.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [36]:
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [37]:
# 1 -> purchased
# 0 -> not purchased

In [38]:
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [39]:
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [40]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

Splitting data into Training and Test set

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=1)

In [42]:
print(X_train)

     Age  EstimatedSalary
82    20            49000
367   46            88000
179   31            34000
27    47            30000
89    35            50000
..   ...              ...
255   52            90000
72    20            23000
396   51            23000
235   46            79000
37    30            49000

[300 rows x 2 columns]


In [43]:
print(X_test)

     Age  EstimatedSalary
398   36            33000
125   39            61000
328   36           118000
339   39           122000
172   26           118000
..   ...              ...
300   58            38000
277   49            88000
289   37            78000
260   35            77000
173   34            43000

[100 rows x 2 columns]


In [44]:
print(y_train)

82     0
367    1
179    0
27     1
89     0
      ..
255    1
72     0
396    1
235    1
37     0
Name: Purchased, Length: 300, dtype: int64


Feature Scaling

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [46]:
print(X_train)
print(X_test)

[[-1.68062015e+00 -5.92416706e-01]
 [ 8.69241193e-01  5.63566526e-01]
 [-6.01832657e-01 -1.03702564e+00]
 [ 9.67312783e-01 -1.15558802e+00]
 [-2.09546297e-01 -5.62776110e-01]
 [ 1.82740063e-01  8.00691292e-01]
 [-4.05689477e-01  1.30458142e+00]
 [ 1.16345596e+00  5.04285335e-01]
 [ 7.71169603e-01  2.96801165e-01]
 [ 6.73098013e-01 -8.88822663e-01]
 [ 3.78883243e-01 -2.96010749e-01]
 [ 4.76954833e-01 -4.73854323e-01]
 [-2.09546297e-01  1.18957591e-01]
 [ 3.78883243e-01  8.93169951e-02]
 [-9.94119017e-01  8.00691292e-01]
 [-6.99904247e-01  1.39350321e+00]
 [ 3.78883243e-01 -5.03494919e-01]
 [ 3.78883243e-01 -5.03494919e-01]
 [-1.68062015e+00  3.85722952e-01]
 [ 8.69241193e-01 -8.29541472e-01]
 [-9.94119017e-01 -1.12594743e+00]
 [-2.09546297e-01  5.96763994e-02]
 [ 1.16345596e+00 -1.21486922e+00]
 [-2.09546297e-01  6.52488313e-01]
 [-1.34031173e-02  1.78238782e-01]
 [-5.03761067e-01  1.42314380e+00]
 [-1.11474707e-01  1.78238782e-01]
 [-1.68062015e+00  5.04285335e-01]
 [ 8.46684727e-02 -5

Training the Decision tree clsssification model

In [47]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion ='entropy', random_state=0)

In [48]:
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

Predicting for new data

In [49]:
print(classifier.predict(sc.transform([[30,87000]])))

[0]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Predicting the Test data

In [50]:
y_pred = classifier.predict(X_test)


In [51]:
print(type(y_pred))

<class 'numpy.ndarray'>


In [52]:
print(type(y_test))

<class 'pandas.core.series.Series'>


In [53]:
y_test = y_test.to_numpy()

In [54]:
# Reshape the NumPy arrays
y_pred = y_pred.reshape(len(y_pred), 1)
y_test = y_test.reshape(len(y_test), 1)

# Now concatenate
result = np.concatenate((y_pred, y_test), axis=1)

# Print the result
print(result)

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]]


In [55]:
## [0,0] and [1,1] represent correct prediction and rest combination represnrt incorrect prediction

Making the Confusion matrix

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [57]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[48 10]
 [ 7 35]]


In [58]:
## 48 is TP , 35 is TN

In [59]:
accuracy_score(y_test, y_pred)

0.83

In [1]:
#  model correctly predicted 83% times